[build]
builder = "nixpacks"
buildCommand = "bundle install && bundle exec rails assets:precompile"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "bundle exec rails server -p $PORT -e production"

[environments.production.variables]
RAILS_ENV = "production"
SELF_HOSTED = "true"
RAILS_FORCE_SSL = "true"
RAILS_ASSUME_SSL = "true"
PORT = "3000" 